title    MeoArch OS - terminal only (%ARCH%, UEFI)
sort-key 03
linux    /%INSTALL_DIR%/boot/%ARCH%/vmlinuz-linux
initrd   /%INSTALL_DIR%/boot/%ARCH%/initramfs-linux.img
options  archisobasedir=%INSTALL_DIR% archisosearchuuid=%ARCHISO_UUID% meoarch.mode=tty systemd.unit=multi-user.target plymouth.enable=0 systemd.show_status=1 loglevel=4 vt.global_cursor_default=1
