[Unit]
ConditionPathExists=/run/archiso
ConditionKernelCommandLine=!meoarch.session=cage
ConditionKernelCommandLine=!meoarch.mode=tty
# Do not make graphical startup depend on an online network.
Wants=NetworkManager.service
